export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENT = "INIT_INGREDIENT";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAIL = "PURCHASE_ORDER_FAIL";
export const PURCHASE_START = "PURCHASE_START";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_OREDRS_SUCCESS = "FETCH_OREDRS_SUCCESS";
export const FETCH_OREDRS_FAILED = "FETCH_OREDRS_FAILED";
